//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeebReader.Web.Portal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeebReader.Web.Portal.PortalMessages", typeof(PortalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in..
        /// </summary>
        public static string MSG001 {
            get {
                return ResourceManager.GetString("MSG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account cannot sign in due to too many failed sign in attempts..
        /// </summary>
        public static string MSG002 {
            get {
                return ResourceManager.GetString("MSG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials, please try again..
        /// </summary>
        public static string MSG003 {
            get {
                return ResourceManager.GetString("MSG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is disabled, please contact an administrator..
        /// </summary>
        public static string MSG004 {
            get {
                return ResourceManager.GetString("MSG004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in. Please sign out or change your password in the administrator panel..
        /// </summary>
        public static string MSG005 {
            get {
                return ResourceManager.GetString("MSG005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},\nA password reset was requested at {1}.\nPlease go to the following URL to proceed with the reset. You can safely ignore this e-mail if you didn&apos;t request this.\n{2}.
        /// </summary>
        public static string MSG006 {
            get {
                return ResourceManager.GetString("MSG006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset - {0}.
        /// </summary>
        public static string MSG007 {
            get {
                return ResourceManager.GetString("MSG007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If that address exists in our database, an e-mail will be send with the details on how to proceed with the password reset..
        /// </summary>
        public static string MSG008 {
            get {
                return ResourceManager.GetString("MSG008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot proceed with the password reset because invalid data was supplied..
        /// </summary>
        public static string MSG009 {
            get {
                return ResourceManager.GetString("MSG009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in. Please sign out or change your password in the administrator panel..
        /// </summary>
        public static string MSG010 {
            get {
                return ResourceManager.GetString("MSG010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully. You can now sign in using your new password..
        /// </summary>
        public static string MSG011 {
            get {
                return ResourceManager.GetString("MSG011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not complete your password reset. Please try again or restart the process..
        /// </summary>
        public static string MSG012 {
            get {
                return ResourceManager.GetString("MSG012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested e-mail is already in use..
        /// </summary>
        public static string MSG013 {
            get {
                return ResourceManager.GetString("MSG013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail was changed successfully..
        /// </summary>
        public static string MSG014 {
            get {
                return ResourceManager.GetString("MSG014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not change your e-mail. Please try again or contact an administrator..
        /// </summary>
        public static string MSG015 {
            get {
                return ResourceManager.GetString("MSG015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not change your password, please verify your password and try again..
        /// </summary>
        public static string MSG016 {
            get {
                return ResourceManager.GetString("MSG016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},\nAn e-mail change was requested at {1}.\nPlease go to the following URL to proceed with the change. If you changed your mind, you can safely ignore this e-mail.\n{2}.
        /// </summary>
        public static string MSG017 {
            get {
                return ResourceManager.GetString("MSG017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change E-mail - {0}.
        /// </summary>
        public static string MSG018 {
            get {
                return ResourceManager.GetString("MSG018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail was sent to the new e-mail with the details on how to proceed with the change..
        /// </summary>
        public static string MSG019 {
            get {
                return ResourceManager.GetString("MSG019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not send a confirmation e-mail, please try again or contact an administrator..
        /// </summary>
        public static string MSG020 {
            get {
                return ResourceManager.GetString("MSG020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MSG021 {
            get {
                return ResourceManager.GetString("MSG021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MSG022 {
            get {
                return ResourceManager.GetString("MSG022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string MSG023 {
            get {
                return ResourceManager.GetString("MSG023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string MSG024 {
            get {
                return ResourceManager.GetString("MSG024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string MSG025 {
            get {
                return ResourceManager.GetString("MSG025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string MSG026 {
            get {
                return ResourceManager.GetString("MSG026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string MSG027 {
            get {
                return ResourceManager.GetString("MSG027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MSG028 {
            get {
                return ResourceManager.GetString("MSG028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MSG029 {
            get {
                return ResourceManager.GetString("MSG029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website uses cookies to personalize your user experience. By using our website, you agree to our use of cookies..
        /// </summary>
        public static string MSG030 {
            get {
                return ResourceManager.GetString("MSG030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string MSG031 {
            get {
                return ResourceManager.GetString("MSG031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string MSG032 {
            get {
                return ResourceManager.GetString("MSG032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your e-mail.
        /// </summary>
        public static string MSG033 {
            get {
                return ResourceManager.GetString("MSG033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string MSG034 {
            get {
                return ResourceManager.GetString("MSG034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string MSG035 {
            get {
                return ResourceManager.GetString("MSG035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string MSG036 {
            get {
                return ResourceManager.GetString("MSG036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        public static string MSG037 {
            get {
                return ResourceManager.GetString("MSG037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MSG038 {
            get {
                return ResourceManager.GetString("MSG038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MSG039 {
            get {
                return ResourceManager.GetString("MSG039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string MSG040 {
            get {
                return ResourceManager.GetString("MSG040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset it..
        /// </summary>
        public static string MSG041 {
            get {
                return ResourceManager.GetString("MSG041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords must be equal..
        /// </summary>
        public static string MSG042 {
            get {
                return ResourceManager.GetString("MSG042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string MSG043 {
            get {
                return ResourceManager.GetString("MSG043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string MSG044 {
            get {
                return ResourceManager.GetString("MSG044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string MSG045 {
            get {
                return ResourceManager.GetString("MSG045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the Password.
        /// </summary>
        public static string MSG046 {
            get {
                return ResourceManager.GetString("MSG046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string MSG047 {
            get {
                return ResourceManager.GetString("MSG047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mails must be equal..
        /// </summary>
        public static string MSG048 {
            get {
                return ResourceManager.GetString("MSG048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string MSG049 {
            get {
                return ResourceManager.GetString("MSG049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string MSG050 {
            get {
                return ResourceManager.GetString("MSG050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New e-mail address.
        /// </summary>
        public static string MSG051 {
            get {
                return ResourceManager.GetString("MSG051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new e-mail address.
        /// </summary>
        public static string MSG052 {
            get {
                return ResourceManager.GetString("MSG052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string MSG053 {
            get {
                return ResourceManager.GetString("MSG053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MSG054 {
            get {
                return ResourceManager.GetString("MSG054", resourceCulture);
            }
        }
    }
}
