//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeebReader.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OtherMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeebReader.Web.Localization.OtherMessages", typeof(OtherMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in..
        /// </summary>
        public static string AlreadySignedIn {
            get {
                return ResourceManager.GetString("AlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in. Please sign out or change your password in the administrator panel..
        /// </summary>
        public static string AlreadySignedInChangePassword {
            get {
                return ResourceManager.GetString("AlreadySignedInChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail was sent to the new e-mail with the details on how to proceed with the change..
        /// </summary>
        public static string ChangeEmailSent {
            get {
                return ResourceManager.GetString("ChangeEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter added successfully..
        /// </summary>
        public static string ChapterAddedSuccessfully {
            get {
                return ResourceManager.GetString("ChapterAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter deleted successfully..
        /// </summary>
        public static string ChapterDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ChapterDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter updated successfully..
        /// </summary>
        public static string ChapterUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ChapterUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this chapter?.
        /// </summary>
        public static string ConfirmDeleteChapter {
            get {
                return ResourceManager.GetString("ConfirmDeleteChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this post?.
        /// </summary>
        public static string ConfirmDeletePost {
            get {
                return ResourceManager.GetString("ConfirmDeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this title?.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this user?.
        /// </summary>
        public static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website uses cookies to personalize your user experience. By using our website, you agree to our use of cookies..
        /// </summary>
        public static string CookieNotice {
            get {
                return ResourceManager.GetString("CookieNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not change your e-mail. Please try again or contact an administrator..
        /// </summary>
        public static string CouldNotChangeEmail {
            get {
                return ResourceManager.GetString("CouldNotChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not complete your password reset. Please try again or restart the process..
        /// </summary>
        public static string CouldNotChangePassword {
            get {
                return ResourceManager.GetString("CouldNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not send a confirmation e-mail, please try again or contact an administrator..
        /// </summary>
        public static string CouldNotSendConfirmationEmail {
            get {
                return ResourceManager.GetString("CouldNotSendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t verify that you&apos;re not a robot..
        /// </summary>
        public static string CouldntVerifyRobot {
            get {
                return ResourceManager.GetString("CouldntVerifyRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is disabled, please contact an administrator..
        /// </summary>
        public static string DisableFunctionality {
            get {
                return ResourceManager.GetString("DisableFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If that address exists in our database, an e-mail will be send with the details on how to proceed with the password reset..
        /// </summary>
        public static string EmailAlreadyInDatabaseWarning {
            get {
                return ResourceManager.GetString("EmailAlreadyInDatabaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail was changed successfully..
        /// </summary>
        public static string EmailChangedSuccessfully {
            get {
                return ResourceManager.GetString("EmailChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeebReader installed successfully. You can now sign-in..
        /// </summary>
        public static string InstalledSuccessfully {
            get {
                return ResourceManager.GetString("InstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message couldn&apos;t be sent..
        /// </summary>
        public static string MessageCouldntBeSent {
            get {
                return ResourceManager.GetString("MessageCouldntBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message from {0}.
        /// </summary>
        public static string MessageFrom {
            get {
                return ResourceManager.GetString("MessageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent. Our team will answer you as soon as possible..
        /// </summary>
        public static string MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chapter exist in the database for the specified title..
        /// </summary>
        public static string NoChapterExist {
            get {
                return ResourceManager.GetString("NoChapterExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no next chapter..
        /// </summary>
        public static string NoNextChapter {
            get {
                return ResourceManager.GetString("NoNextChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No post exist in the database..
        /// </summary>
        public static string NoPostExist {
            get {
                return ResourceManager.GetString("NoPostExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no previous chapter..
        /// </summary>
        public static string NoPreviousChapter {
            get {
                return ResourceManager.GetString("NoPreviousChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title exist in the database..
        /// </summary>
        public static string NoTitleExist {
            get {
                return ResourceManager.GetString("NoTitleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user exist in the database..
        /// </summary>
        public static string NoUserExist {
            get {
                return ResourceManager.GetString("NoUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters updated successfully..
        /// </summary>
        public static string ParametersUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ParametersUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully. You can now sign in using your new password..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot proceed with the password reset because invalid data was supplied..
        /// </summary>
        public static string PasswordResetInvalidData {
            get {
                return ResourceManager.GetString("PasswordResetInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post added successfully..
        /// </summary>
        public static string PostAddedSuccessfully {
            get {
                return ResourceManager.GetString("PostAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post deleted successfully..
        /// </summary>
        public static string PostDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PostDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post updated successfully..
        /// </summary>
        public static string PostUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PostUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened. Please try again or contact an administrator..
        /// </summary>
        public static string RequestFailed {
            get {
                return ResourceManager.GetString("RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parameters failed to update..
        /// </summary>
        public static string SomeParametersFailedToUpdate {
            get {
                return ResourceManager.GetString("SomeParametersFailedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong is not right..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title added successfully..
        /// </summary>
        public static string TitleAddedSuccessfully {
            get {
                return ResourceManager.GetString("TitleAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title deleted successfully..
        /// </summary>
        public static string TitleDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TitleDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title updated successfully..
        /// </summary>
        public static string TitleUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TitleUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account cannot sign in due to too many failed sign in attempts..
        /// </summary>
        public static string TooManyFailedSignIn {
            get {
                return ResourceManager.GetString("TooManyFailedSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully. A message was sent to the user&apos;s e-mail with instructions on how to proceed..
        /// </summary>
        public static string UserCreatedEmailSent {
            get {
                return ResourceManager.GetString("UserCreatedEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully..
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
