//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeebReader.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OtherMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeebReader.Web.Localization.OtherMessages", typeof(OtherMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in..
        /// </summary>
        public static string AlreadySignedIn {
            get {
                return ResourceManager.GetString("AlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already signed in. Please sign out or change your password in the administrator panel..
        /// </summary>
        public static string AlreadySignedInChangePassword {
            get {
                return ResourceManager.GetString("AlreadySignedInChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail was sent to the new e-mail with the details on how to proceed with the change..
        /// </summary>
        public static string ChangeEmailSent {
            get {
                return ResourceManager.GetString("ChangeEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website uses cookies to personalize your user experience. By using our website, you agree to our use of cookies..
        /// </summary>
        public static string CookieNotice {
            get {
                return ResourceManager.GetString("CookieNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not change your e-mail. Please try again or contact an administrator..
        /// </summary>
        public static string CouldNotChangeEmail {
            get {
                return ResourceManager.GetString("CouldNotChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not complete your password reset. Please try again or restart the process..
        /// </summary>
        public static string CouldNotChangePassword {
            get {
                return ResourceManager.GetString("CouldNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not send a confirmation e-mail, please try again or contact an administrator..
        /// </summary>
        public static string CouldNotSendConfirmationEmail {
            get {
                return ResourceManager.GetString("CouldNotSendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is disabled, please contact an administrator..
        /// </summary>
        public static string DisableFunctionality {
            get {
                return ResourceManager.GetString("DisableFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If that address exists in our database, an e-mail will be send with the details on how to proceed with the password reset..
        /// </summary>
        public static string EmailAlreadyInDatabaseWarning {
            get {
                return ResourceManager.GetString("EmailAlreadyInDatabaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail was changed successfully..
        /// </summary>
        public static string EmailChangedSuccessfully {
            get {
                return ResourceManager.GetString("EmailChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeebReader installed successfully. You can now sign-in..
        /// </summary>
        public static string InstalledSuccessfully {
            get {
                return ResourceManager.GetString("InstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users were found..
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully. You can now sign in using your new password..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot proceed with the password reset because invalid data was supplied..
        /// </summary>
        public static string PasswordResetInvalidData {
            get {
                return ResourceManager.GetString("PasswordResetInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong is not right..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account cannot sign in due to too many failed sign in attempts..
        /// </summary>
        public static string TooManyFailedSignIn {
            get {
                return ResourceManager.GetString("TooManyFailedSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully. A message was sent to the user&apos;s e-mail with instructions on how to proceed..
        /// </summary>
        public static string UserCreatedEmailSent {
            get {
                return ResourceManager.GetString("UserCreatedEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully..
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
